Migrated CI to Talos Linux for consistency (#392)
* Migrated CI to Talos Linux for consistency

* Update Homebrew installation step

* remove brew in favor of talos install script

* Fix typo in talos command to create the cluster

* test

* Updates

* Make CI env like prod

* fix

* fix typo

* Update infrastructure reconciliation

* Fixes

* test

* fix

* remove sandbox

* Add flux-alerter

* fix

* fix

* fix

* Allow manual deployments with ping

* Add commented code for later

* fix

* fix

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -6,6 +6,8 @@ env:
 on:
   pull_request:
     branches: [main]
+  push:
+    branches: [main]
 
 jobs:
   validate-manifests:
@@ -20,36 +22,26 @@ jobs:
       - name: Setup kustomize
         uses: fluxcd/pkg/actions/kustomize@main
       - name: Validate manifests
-        run: $SCRIPTS_DIR/validate-manifests.sh
-  e2e-test:
+        run: $SCRIPTS_DIR/validate-manifests.sh || exit 1
+  verify-and-promote:
     runs-on: ubuntu-latest
-    needs: validate-manifests
-    strategy:
-      matrix:
-        environment: [sandbox] # Add testable environments here.
     steps:
+      - if: github.event_name != 'push'
+        name: Skip
+        run: exit 0
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Setup Flux
-        uses: fluxcd/flux2/action@main
-      - name: Extract branch name
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-      - name: Setup Kubernetes
-        uses: AbsaOSS/k3d-action@v2.4.0
-        with:
-          cluster-name: cluster-ci
-          k3d-version: v5.6.0
-          args: >-
-            --config=$SCRIPTS_DIR/k3d-config.yaml
-      - name: Install Flux
-        run: flux install
-      - name: Setup cluster reconciliation
-        run: $SCRIPTS_DIR/e2e-setup-cluster-reconciliation.sh ${{ github.event.repository.html_url }} ${{ steps.extract_branch.outputs.branch }} ${{ matrix.environment }} ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
-      - name: Verify cluster reconciliation
-        run: $SCRIPTS_DIR/e2e-verify-cluster-reconciliation.sh
-      # Run e2e tests for apps here
-      # ...
-      - name: Debug failure
-        if: failure()
-        run: $SCRIPTS_DIR/e2e-debug-failure.sh
+      # - uses: autotelic/action-wait-for-status-check@v1
+      #   id: wait-for-status
+      #   with:
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     statusName: "kustomization/flux-system"
+      # - name: Promote deployment to production
+      #   if: steps.wait-for-status.outputs.state == 'success'
+      #   uses: joelwmale/webhook-action@master
+      #   with:
+      #     url: ${{ secrets.WEBHOOK_URL }}
+      #     headers: '{"repository": "joelwmale/webhook-action"}'
+      #     body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
+      # - if: steps.wait-for-status.outputs.state == 'failure'
+      #   run: exit 1
